# Generated by Django 5.1.dev20231208084611 on 2024-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_websitemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemeta',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
